"use client";

import { useEffect, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { AlertTriangle, ArrowRight, CheckCircle2, ShieldAlert, Sparkles, X } from "lucide-react";
import Link from "next/link";
import { Button, buttonVariants } from "@/components/ui/button";
import { formatMoney, formatPercent } from "@/lib/finance-format";
import type { AICFOSignal } from "@/types/analytics";

export function DailyBusinessPulse({ open,onClose,signals,revenue,netProfit,grossMargin,currency,companyName }: { open:boolean;onClose:()=>void;signals:AICFOSignal[];revenue:number;netProfit:number;grossMargin:number;currency:string;companyName:string; }) {
  const [mounted,setMounted]=useState(false); useEffect(()=>setMounted(true),[]);
  useEffect(()=>{ if(!open) return; const old=document.body.style.overflow; document.body.style.overflow="hidden"; return()=>{document.body.style.overflow=old}; },[open]);
  if(!mounted||!open) return null;
  const positives=signals.filter(s=>s.severity==="positive").slice(0,2); const redFlags=signals.filter(s=>s.severity==="high").slice(0,2); const watch=signals.filter(s=>s.severity!=="positive"&&s.severity!=="high").slice(0,2);
  return createPortal(<div className="fixed inset-0 z-[9998] grid place-items-center bg-slate-950/55 p-4 backdrop-blur-md" onMouseDown={e=>e.target===e.currentTarget&&onClose()}>
    <section className="w-full max-w-5xl overflow-hidden rounded-[30px] border bg-background shadow-[0_40px_120px_rgba(15,23,42,.5)] animate-modal-in">
      <header className="relative overflow-hidden bg-gradient-to-br from-indigo-600 via-violet-600 to-sky-500 p-6 text-white sm:p-7"><div className="absolute -right-20 -top-20 size-60 rounded-full bg-white/10 blur-2xl"/><div className="relative flex items-start gap-4"><div className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-white/15"><Sparkles className="size-5"/></div><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-100">Daily Business Pulse</p><h2 className="mt-1 text-2xl font-bold sm:text-3xl">A 60-second overview of {companyName}</h2><p className="mt-2 max-w-2xl text-sm text-indigo-50/90">What is moving well, what needs attention, and which red flags deserve management time first.</p></div><button onClick={onClose} className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-white/10 hover:bg-white/20"><X className="size-4"/></button></div><div className="relative mt-5 grid gap-3 sm:grid-cols-3"><MiniMetric label="Revenue" value={formatMoney(revenue,currency)}/><MiniMetric label="Net profit" value={formatMoney(netProfit,currency)}/><MiniMetric label="Gross margin" value={formatPercent(grossMargin)}/></div></header>
      <div className="grid max-h-[52vh] gap-4 overflow-y-auto p-5 sm:p-6 lg:grid-cols-3"><PulseColumn title="Moving well" subtitle="Positive momentum" icon={<CheckCircle2 className="size-5"/>} className="border-emerald-200 bg-emerald-50/70" iconClass="bg-emerald-500 text-white" items={positives.length?positives:netProfit>0?[{title:"The business is profitable",evidence:`Net profit is ${formatMoney(netProfit,currency)} in the current reporting data.`,action:"Protect the drivers supporting profitability.",severity:"positive"} as AICFOSignal]:[]} empty="No strong positive trend identified yet."/><PulseColumn title="Watch closely" subtitle="Needs management attention" icon={<AlertTriangle className="size-5"/>} className="border-amber-200 bg-amber-50/70" iconClass="bg-amber-500 text-white" items={watch} empty="No additional watch item is currently material."/><PulseColumn title="Red flags" subtitle="Investigate first" icon={<ShieldAlert className="size-5"/>} className="border-red-200 bg-red-50/70" iconClass="bg-red-500 text-white" items={redFlags} empty="No critical red flag identified from available data."/></div>
      <footer className="flex flex-col gap-3 border-t bg-muted/25 p-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><p className="text-sm text-muted-foreground">Management summary, not an audit opinion. Open the evidence before a material decision.</p><div className="flex gap-2"><Link href="/dashboard/intelligence" onClick={onClose} className={buttonVariants({variant:"outline"})}>Open Intelligence Center</Link><Button onClick={onClose}>Continue <ArrowRight className="size-4"/></Button></div></footer>
    </section></div>,document.body);
}
function MiniMetric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/15 bg-white/10 p-3"><p className="text-xs text-indigo-100">{label}</p><p className="mt-1 text-lg font-semibold tabular-nums">{value}</p></div>}
function PulseColumn({title,subtitle,icon,className,iconClass,items,empty}:{title:string;subtitle:string;icon:ReactNode;className:string;iconClass:string;items:AICFOSignal[];empty:string}){return <section className={`rounded-[24px] border p-4 ${className}`}><div className="flex items-center gap-3"><div className={`flex size-10 items-center justify-center rounded-xl ${iconClass}`}>{icon}</div><div><h3 className="font-semibold">{title}</h3><p className="text-xs text-muted-foreground">{subtitle}</p></div></div><div className="mt-4 space-y-3">{items.length?items.map((item,i)=><article key={`${item.title}-${i}`} className="rounded-2xl border bg-background/90 p-3.5 shadow-sm"><p className="text-sm font-semibold">{item.title}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.evidence}</p><p className="mt-2 text-xs"><b>Next:</b> {item.action}</p></article>):<div className="rounded-2xl border border-dashed bg-background/60 p-4 text-xs text-muted-foreground">{empty}</div>}</div></section>}
