"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import {
  ArrowLeft, ArrowRight, BadgeCheck, Bot, BrainCircuit, BriefcaseBusiness, CircleDollarSign,
  LineChart, Pause, Play, PlayCircle, RotateCcw, ShieldCheck, Sparkles, TrendingUp, WalletCards,
} from "lucide-react";

const scenes = [
  { kicker:"1 · Connect", title:"Bring the business together.", body:"Start with the finance data you already have. Later, connected systems such as Xero, Zoho and Tally can feed the same intelligence layer.", question:"Do I need to understand accounting imports?", answer:"No. FinCruiz validates the structure and guides you to the next required step before using the data for management reporting.", action:"Data validated · continue to analysis" },
  { kicker:"2 · Understand", title:"The numbers become a management story.", body:"The accounting mechanics stay underneath. Management sees what changed, why it matters and where attention is required.", question:"What changed this month?", answer:"Revenue grew 9.4%, but receivables grew faster. Profit improved while cash conversion weakened. Collections deserve attention before increasing spend.", action:"Investigate collection risk" },
  { kicker:"3 · Decide", title:"Ask the decision. FinCruiz chooses the model.", body:"A manager should not need to know what a three-way forecast is before asking a business question.", question:"Can we afford to hire 3 people?", answer:"This affects profit, the balance sheet and cash together. I would route this into the Three-Way Forecast and model salary timing, cash buffer and working-capital assumptions.", action:"Open Three-Way Decision Model" },
  { kicker:"4 · Control", title:"Trust includes being able to leave.", body:"Customers can reset a module, reset the workspace, disconnect a source, delete synchronized data or permanently delete their profile with confirmation.", question:"What if I upload the wrong information?", answer:"Reset only that module and replace it. The rest of the company workspace can remain intact.", action:"Reset only this module" },
];
const revenue=[72,76,73,81,86,89,96,101,105,112,118,126];
const cash=[66,64,69,67,62,65,70,68,74,78,75,84];
const months=["Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"];

export default function DemoPage(){
  const [scene,setScene]=useState(0); const [playing,setPlaying]=useState(true); const [question,setQuestion]=useState("Can we afford to hire 3 people?"); const [scenario,setScenario]=useState<"base"|"upside"|"downside">("base");
  useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setScene(v=>(v+1)%scenes.length),6200);return()=>window.clearInterval(id)},[playing]);
  const s=scenes[scene];
  const scenarioData=useMemo(()=>scenario==="upside"?{sales:"+14.20%",cash:"₹8.90M",profit:"₹5.16M",note:"Growth improves while cash buffer stays above target"}:scenario==="downside"?{sales:"-4.80%",cash:"₹3.28M",profit:"₹2.17M",note:"Slower sales + collections 12 days slower"}:{sales:"+8.90%",cash:"₹6.21M",profit:"₹4.12M",note:"Current run-rate and collection assumptions"},[scenario]);
  const answers:Record<string,string>={
    "What should management focus on?":"Collections are the clearest near-term lever. Revenue is rising, but overdue receivables are absorbing more cash. Start with the five largest overdue customers.",
    "Can we afford to hire 3 people?":"FinCruiz would route this into the Three-Way Forecast because hiring changes profit, payroll liabilities and cash together. Under the demo base case the hire is affordable, but the downside case reduces the cash buffer materially.",
    "Why is profit up but cash tight?":"Working capital is the main reason in this sample company. Receivables have grown faster than sales, so accounting profit has not converted into cash at the same pace.",
  };
  return <main className="min-h-screen overflow-hidden bg-[#07101f] text-white"><div className="fixed inset-0 pointer-events-none demo-aurora"/>
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#07101f]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="flex items-center gap-2 text-sm text-slate-300 hover:text-white"><ArrowLeft className="size-4"/>FinCruiz</Link><div className="flex items-center gap-2"><span className="hidden rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1.5 text-xs text-emerald-200 sm:inline-flex"><ShieldCheck className="mr-1.5 size-3.5"/>Interactive demo · synthetic data</span><Link href="/login" className="hidden rounded-xl border border-white/15 px-4 py-2.5 text-sm font-semibold sm:block">Sign in</Link><Link href="/signup" className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-950">Use my business data</Link></div></div></header>

    <section className="relative z-10 mx-auto max-w-7xl px-5 pb-14 pt-10 lg:px-8"><div className="rounded-2xl border border-indigo-300/15 bg-indigo-300/[.07] px-4 py-3 text-sm text-indigo-100 sm:flex sm:items-center sm:justify-between"><span className="flex items-center gap-2"><PlayCircle className="size-4"/><b>You are in Demo Mode.</b>&nbsp; Nothing here uses your data.</span><span className="mt-2 text-xs text-indigo-200 sm:mt-0">Watch the 2-minute story or interact below.</span></div>
      <div className="mt-10 grid items-center gap-10 lg:grid-cols-[.82fr_1.18fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-sky-300/15 bg-sky-300/10 px-3 py-1.5 text-xs font-semibold text-sky-100"><Sparkles className="size-3.5"/>See the Organizational Brain in action</div><h1 className="mt-5 text-4xl font-black tracking-[-.045em] sm:text-6xl">See FinCruiz <span className="bg-gradient-to-r from-sky-300 via-indigo-300 to-violet-300 bg-clip-text text-transparent">think with the business.</span></h1><p className="mt-5 max-w-xl text-base leading-8 text-slate-300 sm:text-lg">No finance knowledge and no login required. Follow a synthetic company from data → insight → management decision.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setPlaying(v=>!v)} className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-5 py-3 text-sm font-bold hover:bg-indigo-400">{playing?<Pause className="size-4"/>:<Play className="size-4"/>}{playing?"Pause guided story":"Continue guided story"}</button><button onClick={()=>{setScene(0);setPlaying(true)}} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold hover:bg-white/10"><RotateCcw className="size-4"/>Restart</button></div><div className="mt-8 grid grid-cols-4 gap-2">{scenes.map((item,index)=><button key={item.kicker} onClick={()=>{setScene(index);setPlaying(false)}} className={`h-1.5 rounded-full transition ${index===scene?"bg-indigo-300":"bg-white/10"}`} aria-label={`Show scene ${index+1}`}/>)}</div></div>
        <div className="relative overflow-hidden rounded-[34px] border border-white/10 bg-white/[.04] p-1 shadow-[0_40px_120px_rgba(20,30,80,.5)]"><div className="min-h-[500px] rounded-[31px] bg-slate-950/75 p-6 backdrop-blur sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.18em] text-indigo-200">{s.kicker}</span><span className="flex items-center gap-2 text-xs text-slate-400"><span className="size-2 animate-pulse rounded-full bg-emerald-400"/>Guided simulation</span></div><div key={scene} className="mt-8 animate-scene-in"><h2 className="text-3xl font-bold sm:text-4xl">{s.title}</h2><p className="mt-4 max-w-2xl leading-7 text-slate-300">{s.body}</p><div className="mt-8 grid gap-4 sm:grid-cols-[.82fr_1.18fr]"><div className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-xs uppercase tracking-wider text-slate-500">Management asks</p><p className="mt-3 text-lg font-semibold">“{s.question}”</p><div className="mt-7 flex gap-2"><span className="demo-dot"/><span className="demo-dot [animation-delay:180ms]"/><span className="demo-dot [animation-delay:360ms]"/></div></div><div className="rounded-2xl border border-indigo-300/15 bg-indigo-300/[.07] p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-200"><Bot className="size-4"/>FinCruiz Intelligence</div><p className="mt-3 text-sm leading-7 text-slate-100">{s.answer}</p><div className="mt-4 rounded-xl bg-white/[.05] px-3 py-2 text-xs text-sky-200"><b>Suggested next step:</b> {s.action}</div></div></div><div className="mt-5 flex items-center gap-3 rounded-2xl border border-emerald-300/10 bg-emerald-300/[.05] p-4 text-sm text-slate-300"><BadgeCheck className="size-5 shrink-0 text-emerald-300"/><span><b className="text-white">Progressive disclosure.</b> Start with the business meaning, then open the calculation and transaction evidence only when needed.</span></div></div></div></div>
      </div>

      <div className="mt-20 text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-300">Now take control</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Ask the sample business a real management question.</h2></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[30px] border border-white/10 bg-white/[.05] p-6"><div className="flex items-center justify-between"><div><p className="font-semibold">Nova Retail · Executive view</p><p className="mt-1 text-xs text-slate-400">Synthetic 12-month history</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs text-emerald-200">Finance data ready</span></div><div className="mt-5 grid grid-cols-3 gap-3">{[["Revenue","₹24.80M"],["Net profit","₹4.12M"],["Cash","₹6.21M"]].map(([l,v])=><div key={l} className="rounded-2xl border border-white/10 bg-slate-950/45 p-4"><p className="text-xs text-slate-400">{l}</p><p className="mt-2 text-xl font-bold">{v}</p></div>)}</div><div className="mt-5 rounded-2xl border border-white/10 bg-slate-950/45 p-5"><div className="flex h-48 items-end gap-2">{revenue.map((height,i)=><div key={months[i]} className="group flex flex-1 flex-col items-center justify-end gap-2"><div className="w-full rounded-t bg-gradient-to-t from-indigo-600 to-sky-300 transition duration-500 group-hover:brightness-125" style={{height:`${height}px`}}/><span className="hidden text-[9px] text-slate-500 sm:block">{months[i]}</span></div>)}</div></div></div>
        <div className="rounded-[30px] border border-indigo-300/15 bg-indigo-300/[.06] p-6"><p className="flex items-center gap-2 text-sm font-bold"><BrainCircuit className="size-5 text-indigo-300"/>Ask FinCruiz</p><div className="mt-4 flex flex-wrap gap-2">{Object.keys(answers).map((item)=><button key={item} onClick={()=>setQuestion(item)} className={`rounded-full border px-3 py-1.5 text-xs ${question===item?"border-indigo-300/40 bg-indigo-300/15 text-indigo-100":"border-white/10 text-slate-300"}`}>{item}</button>)}</div><div key={question} className="mt-5 animate-scene-in rounded-2xl bg-slate-950/55 p-5"><p className="text-xs uppercase tracking-wider text-indigo-300">Management question</p><p className="mt-2 font-semibold">{question}</p><p className="mt-4 text-sm leading-7 text-slate-300">{answers[question]}</p>{question.includes("hire")?<div className="mt-4 flex items-center gap-2 rounded-xl bg-violet-400/10 p-3 text-xs text-violet-200"><TrendingUp className="size-4"/>Recommended tool: Three-Way Forecast</div>:null}</div></div></div>

      <div className="mt-8 rounded-[30px] border border-white/10 bg-white/[.04] p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-violet-300">Three-Way Decision Model</p><h3 className="mt-2 text-2xl font-bold">Watch one assumption flow through the business.</h3><p className="mt-2 text-sm text-slate-400">Profit & Loss → Balance Sheet → Cash Flow</p></div><div className="flex gap-2">{(["base","upside","downside"] as const).map(v=><button key={v} onClick={()=>setScenario(v)} className={`rounded-xl px-4 py-2 text-sm font-semibold capitalize ${scenario===v?"bg-white text-slate-950":"border border-white/10 bg-white/5"}`}>{v}</button>)}</div></div><div key={scenario} className="mt-6 grid animate-scene-in gap-3 md:grid-cols-4">{[["Revenue impact",scenarioData.sales,BriefcaseBusiness],["Closing cash",scenarioData.cash,WalletCards],["Net profit",scenarioData.profit,CircleDollarSign],["Assessment",scenarioData.note,LineChart]].map(([label,value,Icon])=>{const C=Icon as typeof LineChart;return <div key={String(label)} className="rounded-2xl border border-white/10 bg-slate-950/40 p-4"><C className="size-4 text-indigo-300"/><p className="mt-3 text-xs text-slate-400">{String(label)}</p><p className="mt-2 font-bold">{String(value)}</p></div>})}</div></div>

      <div className="mt-16 rounded-[34px] bg-white p-8 text-slate-950 sm:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-indigo-600">Ready when you are</p><h2 className="mt-3 text-3xl font-black">Use the same experience with your own business.</h2><p className="mt-4 max-w-2xl text-slate-600">Create a workspace, connect or upload data, and let FinCruiz build the management view. You remain in control of resets, connections and deletion.</p></div><div className="flex flex-col gap-2"><Link href="/signup" className="inline-flex min-h-13 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-6 font-bold text-white">Create workspace<ArrowRight className="size-4"/></Link><Link href="/login" className="text-center text-sm font-semibold text-slate-600">Already have an account? Sign in</Link></div></div></div>
    </section>
  </main>
}
