"use client";
import {Suspense,useEffect,useState} from "react";import {useRouter,useSearchParams} from "next/navigation";import {Loader2,ShieldCheck} from "lucide-react";
import {Button} from "@/components/ui/button";import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";
import {authService} from "@/services/auth-service";import {companyService} from "@/services/company-service";
function Loading(){return <main className="flex min-h-screen items-center justify-center"><Loader2 className="size-6 animate-spin"/></main>}
function Content(){const q=useSearchParams(),r=useRouter(),token=q.get("token")||"";const[state,setState]=useState("checking"),[err,setErr]=useState(""),[p,setP]=useState({full_name:"",job_title:""});
useEffect(()=>{if(!token){setErr("Invitation link is incomplete.");setState("error")}else setState(authService.hasAccessToken()?"accept":"signin")},[token]);
async function accept(){setState("checking");try{await companyService.acceptAccessInvitation(token);setP(await companyService.getPersonalProfile());setState("profile")}catch(e){setErr(e instanceof Error?e.message:"Invitation failed.");setState("error")}}
async function complete(){setState("checking");try{await companyService.updatePersonalProfile(p);r.replace("/dashboard")}catch(e){setErr(e instanceof Error?e.message:"Profile update failed.");setState("error")}}
return <main className="flex min-h-screen items-center justify-center bg-muted/30 px-6"><Card className="w-full max-w-lg"><CardHeader><ShieldCheck className="size-10 text-primary"/><CardTitle>Secure workspace invitation</CardTitle><CardDescription>Only the invited email can activate this company membership.</CardDescription></CardHeader><CardContent className="space-y-4">{state==="signin"?<><p className="text-sm">Sign in or create an account with the exact invited email.</p><Button className="w-full" onClick={()=>r.push(`/login?next=${encodeURIComponent(`/invite?token=${token}`)}`)}>Sign in</Button><Button variant="outline" className="w-full" onClick={()=>r.push(`/signup?next=${encodeURIComponent(`/invite?token=${token}`)}`)}>Create account</Button></>:null}{state==="accept"?<Button className="w-full" onClick={()=>void accept()}>Verify & accept invitation</Button>:null}{state==="profile"?<><p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">Invitation verified. Complete your profile to activate access.</p><div><Label>Full name</Label><Input className="mt-2" value={p.full_name||""} onChange={e=>setP({...p,full_name:e.target.value})}/></div><div><Label>Job title</Label><Input className="mt-2" value={p.job_title||""} onChange={e=>setP({...p,job_title:e.target.value})}/></div><Button className="w-full" disabled={!p.full_name?.trim()} onClick={()=>void complete()}>Complete profile & activate</Button></>:null}{state==="checking"?<Loader2 className="size-5 animate-spin"/>:null}{state==="error"?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-900">{err}</p>:null}</CardContent></Card></main>}
export default function InvitePage(){return <Suspense fallback={<Loading/>}><Content/></Suspense>}
