"use client";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AlertTriangle, CheckCircle2, Loader2, Play, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { InsightChart } from "@/components/insight-chart";
import { advancedFinanceService } from "@/services/advanced-finance-service";
import { formatMoney } from "@/lib/finance-format";
import type { DecisionSimulation, PlanningBaseline } from "@/types/advanced-forecasting";
import type { AIVisualization } from "@/types/analytics";

const base = {
  run_name: "Management Decision Scenario", forecast_start: "2027-01-01", forecast_months: 24,
  trend_weight: .45, budget_weight: .35, run_rate_weight: .2, seasonality_enabled: true,
  revenue_change_percent: 0, price_change_percent: 0, volume_change_percent: 0, gross_margin_points: 0,
  headcount_change: 0, monthly_cost_per_hire: 0, payroll_change_percent: 0, other_opex_change_percent: 0,
  dso_change_days: 0, dpo_change_days: 0, inventory_change_days: 0, capex_change_percent: 0,
  drivers: { gross_margin:.42,payroll_pct_revenue:.22,other_opex_pct_revenue:.14,annual_interest_rate:.075,tax_rate:.30,dso_days:42,dpo_days:35,inventory_days:45,capex_pct_revenue:.04,useful_life_months:60,scheduled_debt_repayment:10000,minimum_cash:100000,revolver_limit:500000,dividend_pct_net_income:0 },
  opening_balance_sheet: { cash:250000,accounts_receivable:300000,inventory:180000,other_current_assets:40000,gross_ppe:600000,accumulated_depreciation:-140000,other_non_current_assets:25000,accounts_payable:210000,accrued_expenses:75000,other_current_liabilities:35000,debt_current:60000,debt_non_current:420000,other_non_current_liabilities:20000,share_capital:200000,retained_earnings:null }
};
const assumptions = [
  ["revenue_change_percent","Revenue change","%","Across the scenario horizon"], ["price_change_percent","Price change","%","Changes revenue while preserving volume"],
  ["volume_change_percent","Volume change","%","Changes revenue volume"], ["gross_margin_points","Gross margin","pts","Percentage-point movement"],
  ["headcount_change","Headcount change","people","Added or removed employees"], ["monthly_cost_per_hire","Monthly cost / hire","currency","Salary plus employer cost"],
  ["payroll_change_percent","Other payroll change","%","Across existing payroll"], ["other_opex_change_percent","Other opex change","%","Operating expense movement"],
  ["dso_change_days","Customer payment days","days","Positive = customers pay slower"], ["dpo_change_days","Supplier payment days","days","Positive = suppliers paid later"],
  ["inventory_change_days","Inventory days","days","Positive = more stock held"], ["capex_change_percent","Capex change","%","Capital expenditure movement"],
] as const;

export default function DecisionSimulatorPage(){
  const params=useSearchParams(); const [form,setForm]=useState<any>(base); const [baseline,setBaseline]=useState<PlanningBaseline|null>(null); const [result,setResult]=useState<DecisionSimulation|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{const scenario=params.get("scenario");const headcount=Number(params.get("headcount_change")||0);if(scenario||headcount){setForm((f:any)=>({...f,run_name:`AI scenario — ${scenario||"Management decision"}`,headcount_change:headcount}))}},[params]);
  useEffect(()=>{advancedFinanceService.planningBaseline().then(b=>{setBaseline(b);setForm((f:any)=>({...f,forecast_start:String(b.suggested_forecast_start).slice(0,10),drivers:{...f.drivers,gross_margin:b.gross_margin_percent/100,payroll_pct_revenue:b.payroll_percent_revenue/100,other_opex_pct_revenue:b.other_opex_percent_revenue/100},opening_balance_sheet:{...f.opening_balance_sheet,...b.opening_balance_sheet}}))}).catch(()=>undefined)},[]);
  async function run(){setLoading(true);setError("");try{setResult(await advancedFinanceService.simulateDecision(form))}catch(e:any){setError(e?.response?.data?.detail||e?.message||"Unable to run scenario") }finally{setLoading(false)}}
  const cashChart=useMemo<AIVisualization|null>(()=>result?({type:"line",title:"Cash — Base vs Scenario",subtitle:"Monthly closing cash from the integrated three-way model",labels:result.comparison_series.map(x=>x.period.slice(0,7)),series:[{name:"Base",data:result.comparison_series.map(x=>x.base_cash)},{name:"Scenario",data:result.comparison_series.map(x=>x.scenario_cash)}],value_format:"currency",currency:"AUD"}):null,[result]);
  const profitChart=useMemo<AIVisualization|null>(()=>result?({type:"bar",title:"Net Profit — Base vs Scenario",subtitle:"Monthly net income impact",labels:result.comparison_series.map(x=>x.period.slice(0,7)),series:[{name:"Base",data:result.comparison_series.map(x=>x.base_net_income)},{name:"Scenario",data:result.comparison_series.map(x=>x.scenario_net_income)}],value_format:"currency",currency:"AUD"}):null,[result]);
  return <div className="mx-auto max-w-7xl space-y-6 pb-12">
    <div className="overflow-hidden rounded-3xl border bg-gradient-to-br from-violet-50 via-background to-sky-50 p-6 dark:from-violet-950/25 dark:to-sky-950/20"><div className="flex items-start gap-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-2xl bg-violet-600 text-white shadow-lg"><Sparkles className="size-5"/></div><div><p className="text-sm font-medium text-violet-700 dark:text-violet-300">Decision Intelligence</p><h1 className="mt-1 text-3xl font-semibold">Management Decision Simulator</h1><p className="mt-2 max-w-3xl text-muted-foreground">Test a management decision before making it. Assumptions flow through Revenue, P&amp;L, Balance Sheet, working capital and Cash Flow together. FinCruiz calculates the numbers; AI can explain the result.</p></div></div></div>
    {baseline?<Card className="border-sky-200 bg-sky-50/40 dark:border-sky-900 dark:bg-sky-950/10"><CardHeader><CardTitle>Base business position</CardTitle><CardDescription>FinCruiz has prefilled the model from your mapped actuals and current balance-sheet structure. The fields below are changes from this base, not a blank financial model.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><BaseMetric label="Trailing revenue" value={formatMoney(baseline.trailing_revenue)}/><BaseMetric label="Gross margin" value={`${baseline.gross_margin_percent.toFixed(2)}%`}/><BaseMetric label="Payroll / revenue" value={`${baseline.payroll_percent_revenue.toFixed(2)}%`}/><BaseMetric label="Operating costs" value={formatMoney(baseline.trailing_opex)}/><BaseMetric label="History used" value={`${baseline.history_months} months`}/></CardContent></Card>:null}
    <Card><CardHeader><CardTitle>What do you want to test?</CardTitle><CardDescription>Use only the assumptions relevant to your decision. Zero means no change from the base forecast.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><label className="space-y-1.5 text-sm md:col-span-2"><span>Scenario name</span><Input value={form.run_name} onChange={e=>setForm({...form,run_name:e.target.value})}/></label><label className="space-y-1.5 text-sm"><span>Forecast months</span><Input type="number" min={1} max={60} value={form.forecast_months} onChange={e=>setForm({...form,forecast_months:Number(e.target.value)})}/></label></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{assumptions.map(([key,label,unit,help])=><label key={key} className="rounded-2xl border bg-muted/20 p-3 text-sm"><span className="font-medium">{label}</span><span className="ml-1 text-xs text-muted-foreground">({unit})</span><Input className="mt-2" type="number" step="0.01" value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/><span className="mt-1.5 block text-[11px] text-muted-foreground">{help}</span></label>)}</div><div className="flex flex-wrap items-center gap-3"><Button onClick={()=>void run()} disabled={loading} size="lg">{loading?<Loader2 className="size-4 animate-spin"/>:<Play className="size-4"/>}Run decision model</Button><span className="text-xs text-muted-foreground">Nothing is posted to your ledger. This is a forecast simulation only.</span></div>{error?<p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}</CardContent></Card>
    {result?<><Assessment result={result}/><div className="grid gap-4 md:grid-cols-3"><ImpactCard label="Closing cash impact" value={result.impact.closing_cash}/><ImpactCard label="Net profit impact" value={result.impact.forecast_net_income}/><ImpactCard label="Revenue impact" value={result.impact.forecast_revenue}/></div><div className="grid gap-5 xl:grid-cols-2">{cashChart?<InsightChart visualization={cashChart}/>:null}{profitChart?<InsightChart visualization={profitChart}/>:null}</div><Card><CardHeader><CardTitle>Base vs Scenario</CardTitle><CardDescription>Key outputs from the same integrated model.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Closing cash","closing_cash"],["Minimum cash","minimum_cash"],["Net income","forecast_net_income"],["Closing debt","closing_debt"]].map(([label,key])=><div key={key} className="rounded-2xl border p-4"><p className="text-xs text-muted-foreground">{label}</p><div className="mt-3 flex items-end justify-between gap-3"><div><p className="text-xs text-muted-foreground">Base</p><p className="font-semibold">{formatMoney(Number(result.base_summary[key]||0))}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Scenario</p><p className="font-semibold">{formatMoney(Number(result.scenario_summary[key]||0))}</p></div></div></div>)}</div></CardContent></Card></>:null}
  </div>
}
function Assessment({result}:{result:DecisionSimulation}){const red=result.assessment.level==="red",amber=result.assessment.level==="amber";const Icon=red?AlertTriangle:amber?TrendingDown:CheckCircle2;return <Card className={red?"border-red-300 bg-red-50/60 dark:bg-red-950/15":amber?"border-amber-300 bg-amber-50/60 dark:bg-amber-950/15":"border-emerald-300 bg-emerald-50/60 dark:bg-emerald-950/15"}><CardContent className="flex gap-4 p-5"><div className="mt-0.5"><Icon className={red?"size-6 text-red-600":amber?"size-6 text-amber-600":"size-6 text-emerald-600"}/></div><div><p className="font-semibold">{result.assessment.title}</p><p className="mt-1 text-sm text-muted-foreground">{result.assessment.message}</p>{result.scenario_summary.first_cash_pressure_month?<p className="mt-2 text-sm font-medium">First cash-pressure month: {String(result.scenario_summary.first_cash_pressure_month).slice(0,7)}</p>:null}</div></CardContent></Card>}
function ImpactCard({label,value}:{label:string;value:number}){const positive=value>=0;return <Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><div className="mt-2 flex items-center gap-2">{positive?<TrendingUp className="size-5 text-emerald-600"/>:<TrendingDown className="size-5 text-red-600"/>}<p className="text-2xl font-semibold">{value>=0?"+":""}{formatMoney(value)}</p></div></CardContent></Card>}

function BaseMetric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-background p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
