"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Building2, Check, Loader2, LogOut, Rocket, ShieldCheck, Sparkles } from "lucide-react";

import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getApiErrorMessage } from "@/lib/api";
import { authService } from "@/services/auth-service";
import { companyService } from "@/services/company-service";
import { MARKET_CONFIGS, marketForCountry } from "@/lib/market-config";

const industries=["Professional services","Retail / eCommerce","Manufacturing","Transport / logistics","Construction","Healthcare","Technology / SaaS","Hospitality","Wholesale / distribution","Other"];
const models=["Service business","Product / retail","Subscription","Marketplace","Project-based","Mixed model"];

export default function OnboardingPage(){
  const router=useRouter(); const [step,setStep]=useState(0); const [checking,setChecking]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const [legalName,setLegalName]=useState(""); const [tradingName,setTradingName]=useState(""); const [countryCode,setCountryCode]=useState("AU"); const [currencyCode,setCurrencyCode]=useState("AUD"); const [fye,setFye]=useState("6");
  const [industry,setIndustry]=useState(""); const [businessModel,setBusinessModel]=useState(""); const [employees,setEmployees]=useState(""); const [revenue,setRevenue]=useState(""); const [website,setWebsite]=useState(""); const [abn,setAbn]=useState("");
  useEffect(()=>{(async()=>{if(!authService.hasAccessToken()){router.replace("/login");return;} try{await companyService.getCurrentCompany();router.replace("/dashboard");return;}catch{} try{const u=await authService.getCurrentUser();const d=(u.user_metadata?.company_details??{}) as Record<string,unknown>; if(d.legal_name)setLegalName(String(d.legal_name)); if(d.trading_name)setTradingName(String(d.trading_name)); if(d.industry)setIndustry(String(d.industry)); if(d.business_model)setBusinessModel(String(d.business_model));}catch{} setChecking(false);})()},[router]);
  const canContinue=useMemo(()=>step===0?legalName.trim().length>=2:step===1?Boolean(industry&&businessModel):true,[step,legalName,industry,businessModel]);
  async function submit(e:FormEvent){e.preventDefault(); if(step<2){setStep(v=>v+1);return;} setSaving(true);setError("");try{await companyService.createCompany({legal_name:legalName.trim(),trading_name:tradingName.trim()||null,abn:abn.trim()||null,country_code:countryCode.toUpperCase(),currency_code:currencyCode.toUpperCase(),financial_year_end_month:Number(fye),industry:industry||null,business_model:businessModel||null,employee_count:employees?Number(employees):null,annual_revenue:revenue?Number(revenue):null,logo_path:null,website_url:website.trim()||null});router.replace("/dashboard");}catch(err){setError(getApiErrorMessage(err));}finally{setSaving(false)}}
  if(checking)return <main className="flex min-h-screen items-center justify-center"><Loader2 className="mr-2 size-5 animate-spin"/>Preparing your workspace…</main>;
  return <main className="min-h-screen bg-muted/30 px-5 py-8 sm:py-12"><div className="mx-auto max-w-5xl">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2 font-semibold"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4"/></div>FinCruiz</div><Button variant="ghost" onClick={()=>{authService.logout();router.replace("/login")}}><LogOut className="size-4"/>Sign out</Button></div>
    <div className="mt-10 grid gap-8 lg:grid-cols-[.7fr_1.3fr]">
      <aside className="lg:pt-8"><p className="text-sm font-semibold text-primary">About 2 minutes</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Tell us about the business, not your accounting.</h1><p className="mt-4 leading-7 text-muted-foreground">We use these details to make reports, benchmarks and AI guidance more relevant. You can change everything later.</p><div className="mt-8 space-y-4">{[["1","Your business"],["2","How you operate"],["3","Ready to explore"]].map(([n,label],i)=><div key={n} className={`flex items-center gap-3 ${i<=step?"text-foreground":"text-muted-foreground"}`}><span className={`flex size-8 items-center justify-center rounded-full text-sm font-bold ${i<step?"bg-emerald-100 text-emerald-800":i===step?"bg-primary text-primary-foreground":"bg-muted"}`}>{i<step?<Check className="size-4"/>:n}</span><span className="font-medium">{label}</span></div>)}</div><div className="mt-8 rounded-2xl border bg-card p-4 text-sm text-muted-foreground"><ShieldCheck className="mb-2 size-5 text-emerald-600"/><b className="text-foreground">You stay in control.</b><br/>Use synthetic demo data first, reset individual modules later, or delete the workspace/profile.</div></aside>
      <Card className="overflow-hidden"><CardContent className="p-0"><div className="border-b bg-gradient-to-r from-primary/5 to-transparent p-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground">Step {step+1} of 3</p><h2 className="mt-2 text-2xl font-bold">{step===0?"What should we call your business?":step===1?"Help us understand how you make money":"That is enough to get started."}</h2><p className="mt-2 text-sm text-muted-foreground">{step===0?"Only the legal name is required.":step===1?"This helps the AI choose better language and external context.":"You can explore with demo data before uploading anything real."}</p></div>
        <form onSubmit={submit} className="p-6">{error?<Alert variant="destructive" className="mb-5"><AlertDescription>{error}</AlertDescription></Alert>:null}
          {step===0?<div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label htmlFor="legal">Business / legal name</Label><Input id="legal" className="mt-2" value={legalName} onChange={e=>setLegalName(e.target.value)} placeholder="Example Pty Ltd" required/></div><div><Label>Trading name</Label><Input className="mt-2" value={tradingName} onChange={e=>setTradingName(e.target.value)} placeholder="Optional"/></div><div><Label>{marketForCountry(countryCode).registrationLabel}</Label><Input className="mt-2" value={abn} onChange={e=>setAbn(e.target.value)} placeholder="Optional"/></div><div><Label>Business country</Label><select className="mt-2 w-full rounded-xl border bg-background px-3 py-2 text-sm" value={countryCode} onChange={e=>{const code=e.target.value;const market=marketForCountry(code);setCountryCode(code);setCurrencyCode(market.currencyCode);setFye(String(market.defaultFyeMonth));}}>{Object.values(MARKET_CONFIGS).map(m=><option key={m.countryCode} value={m.countryCode}>{m.countryName}</option>)}</select><p className="mt-1 text-xs text-muted-foreground">This confirmed country drives regional pricing and terminology.</p></div><div><Label>Reporting currency</Label><Input className="mt-2" value={currencyCode} readOnly/></div></div>:null}
          {step===1?<div className="space-y-6"><div><Label>Which best describes your industry?</Label><div className="mt-3 grid gap-2 sm:grid-cols-2">{industries.map(x=><button type="button" key={x} onClick={()=>setIndustry(x)} className={`rounded-xl border p-3 text-left text-sm ${industry===x?"border-primary bg-primary/5 font-semibold":"hover:bg-muted/50"}`}>{x}</button>)}</div></div><div><Label>How does the business mainly earn revenue?</Label><div className="mt-3 flex flex-wrap gap-2">{models.map(x=><button type="button" key={x} onClick={()=>setBusinessModel(x)} className={`rounded-full border px-3 py-2 text-sm ${businessModel===x?"border-primary bg-primary text-primary-foreground":"hover:bg-muted"}`}>{x}</button>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Approx. employees</Label><Input className="mt-2" type="number" min="0" value={employees} onChange={e=>setEmployees(e.target.value)} placeholder="Optional"/></div><div><Label>Approx. annual revenue</Label><Input className="mt-2" type="number" min="0" value={revenue} onChange={e=>setRevenue(e.target.value)} placeholder="Optional"/></div></div></div>:null}
          {step===2?<div><div className="grid gap-3 sm:grid-cols-3">{[[Rocket,"Explore demo first","See the full product with synthetic numbers."],[Building2,"Use my data later","Upload only when you feel comfortable."],[Sparkles,"AI guides me","Ask where to click, what to upload, or what a number means."]].map(([Icon,title,text]:any)=><div key={title} className="rounded-2xl border bg-muted/20 p-4"><Icon className="size-5 text-primary"/><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div>)}</div><div className="mt-6"><Label>Website</Label><Input className="mt-2" value={website} onChange={e=>setWebsite(e.target.value)} placeholder="Optional — helps with business context"/></div><div className="mt-5"><Label>{marketForCountry(countryCode).financialYearLabel} ends in month</Label><select value={fye} onChange={e=>setFye(e.target.value)} className="mt-2 w-full rounded-xl border bg-background px-3 py-2 text-sm">{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2026,i,1).toLocaleString("en",{month:"long"})}</option>)}</select></div></div>:null}
          <div className="mt-8 flex items-center justify-between border-t pt-5"><Button type="button" variant="ghost" disabled={step===0||saving} onClick={()=>setStep(v=>Math.max(0,v-1))}><ArrowLeft className="size-4"/>Back</Button><Button type="submit" disabled={!canContinue||saving}>{saving?<Loader2 className="size-4 animate-spin"/>:step===2?<Rocket className="size-4"/>:<ArrowRight className="size-4"/>}{step===2?"Create my workspace":"Continue"}</Button></div>
        </form></CardContent></Card>
    </div>
  </div></main>
}
