"use client";
import {useEffect,useState} from 'react';import {Plus,Save,Loader2} from 'lucide-react';import {Button} from '@/components/ui/button';import {Card,CardContent,CardHeader,CardTitle,CardDescription} from '@/components/ui/card';import {Input} from '@/components/ui/input';import {advancedFinanceService} from '@/services/advanced-finance-service';import type {PlanningVersion} from '@/types/advanced-forecasting';
const groups=['Revenue','Cost of Sales','Payroll','Operating Expenses','Depreciation','Finance Costs','Tax'];
export default function NativePlanning(){const [versions,setVersions]=useState<PlanningVersion[]>([]),[selected,setSelected]=useState<PlanningVersion|null>(null),[loading,setLoading]=useState(false);const [name,setName]=useState('FY27 Budget');
async function load(){setVersions(await advancedFinanceService.versions())}useEffect(()=>{void load()},[]);
async function create(){setLoading(true);try{const v=await advancedFinanceService.createVersion({plan_type:'budget',version_name:name,financial_year_start:'2027-01-01',financial_year_end:'2027-12-31',seed_from_actuals:true,seed_growth_percent:5});setSelected(v);await load()}finally{setLoading(false)}}
async function open(id:string){setSelected(await advancedFinanceService.getVersion(id))}
function update(i:number,value:string){if(!selected)return;const lines=[...(selected.lines??[])];lines[i]={...lines[i],amount:Number(value)};setSelected({...selected,lines})}
function add(){if(!selected)return;const period=selected.financial_year_start;setSelected({...selected,lines:[...(selected.lines??[]),{period,reporting_group:'Revenue',amount:0,driver_type:'manual',branch_id:null,reporting_subgroup:null,source_account_code:null,driver_value:null,notes:null}]})}
async function save(){if(!selected)return;setLoading(true);try{setSelected(await advancedFinanceService.saveLines(selected.id,selected.lines??[]))}finally{setLoading(false)}}
return <div className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm text-muted-foreground">Planning & intelligence</p><h1 className="text-3xl font-semibold">Native Budget Builder</h1><p className="mt-2 text-muted-foreground">Create, seed, edit and save monthly budgets directly inside FinCruiz.</p></div><div className="grid gap-5 lg:grid-cols-[300px_1fr]"><Card><CardHeader><CardTitle>Versions</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={name} onChange={e=>setName(e.target.value)}/><Button className="w-full" onClick={()=>void create()}><Plus className="size-4"/>New seeded budget</Button>{versions.map(v=><button key={v.id} onClick={()=>void open(v.id)} className="w-full rounded-xl border p-3 text-left hover:bg-muted"><b>{v.version_name}</b><p className="text-xs text-muted-foreground">{v.status} · {v.plan_type}</p></button>)}</CardContent></Card><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{selected?.version_name??'Select a planning version'}</CardTitle><CardDescription>Editable monthly lines; use seed-from-actuals to start quickly.</CardDescription></div>{selected?<div className="flex gap-2"><Button variant="outline" onClick={add}><Plus className="size-4"/>Line</Button><Button onClick={()=>void save()} disabled={loading}>{loading?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Save</Button></div>:null}</CardHeader><CardContent>{!selected?<div className="flex min-h-72 items-center justify-center text-muted-foreground">Create or select a version.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b">{['Period','Reporting group','Subgroup','Amount','Notes'].map(h=><th className="p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{(selected.lines??[]).map((l:any,i)=><tr key={`${l.period}-${l.reporting_group}-${i}`} className="border-b"><td className="p-2"><Input type="date" value={String(l.period).slice(0,10)} onChange={e=>{const lines=[...(selected.lines??[])];lines[i]={...lines[i],period:e.target.value};setSelected({...selected,lines})}}/></td><td className="p-2"><select className="h-10 rounded-md border bg-background px-2" value={l.reporting_group} onChange={e=>{const lines=[...(selected.lines??[])];lines[i]={...lines[i],reporting_group:e.target.value};setSelected({...selected,lines})}}>{groups.map(g=><option key={g}>{g}</option>)}</select></td><td className="p-2"><Input value={l.reporting_subgroup??''}/></td><td className="p-2"><Input type="number" value={l.amount} onChange={e=>update(i,e.target.value)}/></td><td className="p-2"><Input value={l.notes??''}/></td></tr>)}</tbody></table></div>}</CardContent></Card></div></div>}
