"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Bug,CheckCircle2,Eye,Loader2,RefreshCcw,Search} from "lucide-react";
import {Button} from "@/components/ui/button";import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";
import {betaFeedbackService,type BetaFeedbackItem} from "@/services/beta-feedback-service";import {usageService} from "@/services/usage-service";
export default function BetaFeedbackPage(){const[items,setItems]=useState<BetaFeedbackItem[]>([]),[summary,setSummary]=useState<any>(null),[funnel,setFunnel]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState("");
async function load(){setLoading(true);setError("");try{const[i,s,f]=await Promise.all([betaFeedbackService.list(),betaFeedbackService.summary(),usageService.funnel(30)]);setItems(i);setSummary(s);setFunnel(f)}catch(e:any){setError(e?.response?.data?.message||e?.message||'This console is available to workspace owners/admins.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
const visible=useMemo(()=>items.filter(x=>!query.trim()||`${x.title} ${x.description} ${x.category} ${x.status}`.toLowerCase().includes(query.toLowerCase())),[items,query]);async function update(item:BetaFeedbackItem,status:string){await betaFeedbackService.update(item.id,status,item.resolution_notes||undefined);await load()}async function viewAttachment(id:string){const blob=await betaFeedbackService.attachment(id);const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60000)}
return <div className="mx-auto max-w-7xl space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-muted-foreground">Controlled beta</p><h1 className="text-3xl font-semibold">Testing & feedback console</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Prioritise P0/P1 problems, see where testers are using FinCruiz, and close feedback without mixing customer finance values into telemetry.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCcw className={`size-4 ${loading?'animate-spin':''}`}/>Refresh</Button></div>{error?<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{error}</p>:null}
<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Open",summary?.open??0],["P0 open",summary?.p0_open??0],["P1 open",summary?.p1_open??0],["Fixed",summary?.fixed??0],["Total",summary?.total??0]].map(([l,v])=><Card key={String(l)}><CardHeader className="pb-2"><CardDescription>{l}</CardDescription><CardTitle>{v}</CardTitle></CardHeader></Card>)}</div>
<Card><CardHeader><CardTitle>30-day beta usage</CardTitle><CardDescription>Privacy-safe product events only; AI question text and financial values are excluded.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Active users",funnel?.active_users??0],["Page views",funnel?.page_views??0],["AI questions",funnel?.ai_questions??0],["Upload starts",funnel?.upload_starts??0],["Upload completions",funnel?.upload_completions??0],["Front-end errors",funnel?.frontend_errors??0]].map(([l,v])=><div key={String(l)} className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{l}</p><p className="mt-1 text-xl font-semibold">{v}</p></div>)}</CardContent></Card>
<div className="flex items-center gap-2 rounded-xl border bg-background px-3"><Search className="size-4 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search feedback…" className="border-0 shadow-none focus-visible:ring-0"/></div>
<Card><CardHeader><CardTitle>Reported issues & ideas</CardTitle><CardDescription>P0 = security/wrong financial data/core blocker · P1 = must fix before paid launch · P2 = improvement.</CardDescription></CardHeader><CardContent className="space-y-3">{loading?<div className="flex items-center gap-2 p-5 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>Loading beta reports…</div>:visible.length?visible.map(item=><div key={item.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase ${item.severity==='p0'?'bg-red-100 text-red-700':item.severity==='p1'?'bg-amber-100 text-amber-700':'bg-slate-100 text-slate-700'}`}>{item.severity}</span><span className="rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase">{item.status}</span><span className="text-xs text-muted-foreground">{item.category.replaceAll('_',' ')}</span></div><p className="mt-2 font-semibold">{item.title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.description}</p><p className="mt-2 text-xs text-muted-foreground">{item.reporter_name||'Tester'} · {item.user_role||'member'} · {item.path} · {new Date(item.created_at).toLocaleString()}</p>{item.has_attachment?<button type="button" className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-primary" onClick={()=>void viewAttachment(item.id)}><Eye className="size-3.5"/>View authenticated screenshot</button>:null}</div><div className="flex shrink-0 flex-wrap gap-2"><Button size="sm" variant={item.status==='reviewing'?'default':'outline'} onClick={()=>void update(item,'reviewing')}>Reviewing</Button><Button size="sm" variant={item.status==='fixed'?'default':'outline'} onClick={()=>void update(item,'fixed')}><CheckCircle2 className="size-3.5"/>Fixed</Button><Button size="sm" variant="outline" onClick={()=>void update(item,'closed')}>Close</Button></div></div></div>):<p className="p-5 text-sm text-muted-foreground">No matching feedback yet.</p>}</CardContent></Card></div>}
