from dataclasses import dataclass
from decimal import Decimal

from app.domain.finance.reporting.models import BalanceSheetReport, ProfitAndLossReport


@dataclass(frozen=True)
class RatioResult:
    name: str
    category: str
    value: Decimal | None
    unit: str
    status: str
    tone: str
    interpretation: str


def _div(a: Decimal, b: Decimal, multiplier=Decimal("1")):
    return None if b == 0 else a / b * multiplier


def _status(name: str, value: Decimal | None):
    if value is None: return "Not available", "neutral"
    rules = {"Current Ratio":(Decimal("1.5"),Decimal("1"),True),"Quick Ratio":(Decimal("1"),Decimal("0.7"),True),"Debt to Equity":(Decimal("1"),Decimal("2"),False),"Gross Margin":(Decimal("35"),Decimal("20"),True),"Net Profit Margin":(Decimal("10"),Decimal("3"),True),"Return on Assets":(Decimal("8"),Decimal("3"),True),"Return on Equity":(Decimal("15"),Decimal("5"),True),"Asset Turnover":(Decimal("1.5"),Decimal("0.8"),True)}
    rule=rules.get(name)
    if not rule:return "Monitor","neutral"
    good,warn,higher=rule
    if higher:
        return ("Healthy","good") if value>=good else (("Watch","warning") if value>=warn else ("Action required","bad"))
    return ("Healthy","good") if value<=good else (("Watch","warning") if value<=warn else ("Action required","bad"))


def calculate_ratios(pnl: ProfitAndLossReport, bs: BalanceSheetReport, *, inventory=Decimal("0"), cash=Decimal("0"), receivables=Decimal("0"), payables=Decimal("0"), debt=Decimal("0"), period_days=365, employees: Decimal | None=None) -> tuple[RatioResult,...]:
    d=Decimal(str(period_days)); hundred=Decimal("100")
    values=[
        ("Current Ratio","Liquidity",_div(bs.current_assets,bs.current_liabilities),"x","Ability to cover short-term obligations."),
        ("Quick Ratio","Liquidity",_div(bs.current_assets-inventory,bs.current_liabilities),"x","Liquidity excluding inventory."),
        ("DSO","Working Capital",_div(receivables,pnl.revenue,d),"days","Average receivable collection period."),
        ("DPO","Working Capital",_div(payables,pnl.cost_of_sales,d),"days","Average supplier payment period."),
        ("DIO","Working Capital",_div(inventory,pnl.cost_of_sales,d),"days","Average inventory holding period."),
        ("Debt to Equity","Leverage",_div(debt,bs.equity),"x","Debt relative to equity."),
        ("Gross Margin","Profitability",_div(pnl.gross_profit,pnl.revenue,hundred),"%","Gross profit as a percentage of revenue."),
        ("Net Profit Margin","Profitability",_div(pnl.net_profit,pnl.revenue,hundred),"%","Net profit as a percentage of revenue."),
        ("Return on Assets","Returns",_div(pnl.net_profit,bs.total_assets,hundred),"%","Profit generated by assets."),
        ("Return on Equity","Returns",_div(pnl.net_profit,bs.equity,hundred),"%","Return generated on equity."),
        ("Asset Turnover","Efficiency",_div(pnl.revenue,bs.total_assets),"x","Revenue generated per unit of assets."),
    ]
    if employees and employees>0:
        values += [("Revenue per Employee","People Productivity",_div(pnl.revenue,employees),"currency","Revenue generated per employee."),("Net Profit per Employee","People Productivity",_div(pnl.net_profit,employees),"currency","Net profit generated per employee.")]
    result=[]
    for name,cat,val,unit,desc in values:
        status,tone=_status(name,val); result.append(RatioResult(name,cat,val,unit,status,tone,desc))
    dso=next((r.value for r in result if r.name=="DSO"),None); dpo=next((r.value for r in result if r.name=="DPO"),None); dio=next((r.value for r in result if r.name=="DIO"),None)
    ccc=dso+dio-dpo if None not in (dso,dpo,dio) else None; status,tone=_status("Cash Conversion Cycle",ccc)
    result.append(RatioResult("Cash Conversion Cycle","Working Capital",ccc,"days",status,tone,"DSO plus DIO less DPO."))
    return tuple(result)
