"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, KeyRound, Loader2, Save, ShieldCheck, Users, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { companyService } from "@/services/company-service";

type Access={role:string;can_write_finance:boolean;can_reset_all:boolean;can_manage_members:boolean};
type Member={id:string;user_id:string;role:string;is_active:boolean;joined_at:string;full_name:string;job_title?:string|null};
const roleOptions=["admin","cfo","finance_manager","accountant","board_member","viewer"];
export default function AccessPage(){
  const [a,setA]=useState<Access|null>(null);const [members,setMembers]=useState<Member[]>([]);const [saving,setSaving]=useState("");const [error,setError]=useState("");
  async function load(){setError("");try{const [access,people]=await Promise.all([companyService.accessMe(),companyService.accessMembers()]);setA(access);setMembers(people)}catch(e){setError(e instanceof Error?e.message:"Unable to load access controls.")}}
  useEffect(()=>{void load()},[]);
  async function roleChange(id:string,role:string){setSaving(id);setError("");try{await companyService.accessRole(id,role);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update role.")}finally{setSaving("")}}
  if(!a)return <div className="flex min-h-64 items-center justify-center"><Loader2 className="size-5 animate-spin"/></div>;
  const rows=[["View company finance",true],["Upload / change finance data",a.can_write_finance],["Reset individual finance modules",a.can_write_finance],["Reset all workspace finance data",a.can_reset_all],["Manage member roles",a.can_manage_members]] as const;
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-medium text-muted-foreground">Security & access</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">People and permissions</h1><p className="mt-2 text-muted-foreground">Make access understandable: who can view, change, reset, or administer this workspace.</p></div>{error?<div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>:null}
  <div className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><Card className="fincruiz-hero"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5"/>Your current role</CardTitle></CardHeader><CardContent><p className="text-3xl font-bold capitalize">{a.role.replaceAll("_"," ")}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Permissions are evaluated on the backend, not only hidden in the interface.</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="size-5"/>Capability matrix</CardTitle><CardDescription>Destructive actions are deliberately more restricted.</CardDescription></CardHeader><CardContent className="space-y-3">{rows.map(([label,ok])=><div key={label} className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">{label}</span>{ok?<span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><CheckCircle2 className="size-4"/>Allowed</span>:<span className="flex items-center gap-1.5 text-xs font-semibold text-muted-foreground"><XCircle className="size-4"/>Restricted</span>}</div>)}</CardContent></Card></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="size-5"/>Workspace members</CardTitle><CardDescription>{a.can_manage_members?"Owners and admins can change non-owner roles here.":"You can see the team, but only owners/admins can change roles."}</CardDescription></CardHeader><CardContent className="space-y-3">{members.map(m=><div key={m.id} className="flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{m.full_name}</p><p className="mt-1 text-xs text-muted-foreground">{m.job_title||"Workspace member"} · joined {new Date(m.joined_at).toLocaleDateString()}</p></div><div className="flex items-center gap-2">{m.role==="owner"||!a.can_manage_members?<span className="rounded-full bg-muted px-3 py-1.5 text-xs font-semibold capitalize">{m.role.replaceAll("_"," ")}</span>:<><select value={m.role} onChange={e=>void roleChange(m.id,e.target.value)} disabled={saving===m.id} className="rounded-xl border bg-background px-3 py-2 text-sm capitalize">{roleOptions.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select>{saving===m.id?<Loader2 className="size-4 animate-spin text-muted-foreground"/>:<Save className="size-4 text-muted-foreground"/>}</>}</div></div>)}</CardContent></Card>
  </div>}
